services: 
 my-db:
   image: mysql
   environment: 
     MYSQL_ROOT_PASSWORD: pwd1234
   volumes:
    - ./my_data:/var/lib/mysql
   ports:
    - 3306:3306
 my-redis:
    image: redis
    ports:
     - 6379:6379
