services:
  my-sql-service:
    container_name: my-sql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
    volumes: 
      - ./mysql_data:/var/lib/mysql
    ports : 
      - 3306:3306